# Generated by Django 3.1.7 on 2021-03-24 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=20)),
                ('groupDesc', models.TextField(blank=True, null=True)),
                ('groupProfilePic', models.FileField(blank=True, null=True, upload_to='group_<django.db.models.fields.AutoField>')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
