# Generated by Django 3.1.7 on 2021-03-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupProfilePic',
        ),
    ]
