# Generated by Django 3.1.7 on 2021-03-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_remove_group_groupprofilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user1',
            new_name='fromUser',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user2',
            new_name='toUser',
        ),
    ]
