# Generated by Django 3.1.7 on 2021-03-24 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('dp', models.FileField(blank=True, null=True, upload_to=user.models.user_directory_path)),
                ('lastOnline', models.DateTimeField(auto_now_add=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('isPrivate', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
